# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.1
language: objective-c
xcode_project: NotificationBubbles.xcworkspace # path to your xcodeproj folder
xcode_scheme: NotificationBubbles_Example
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone 5s
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
 - gem install cocoapods # Since Travis is not always on latest version
 - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/NotificationBubbles.xcworkspace -scheme NotificationBubbles-Example -sdk iphonesimulator12.1 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
